---
- name:  Ubuntu -  Cache update
  package:
    name: '*'
    state: latest
    force_apt_get: yes
  when: ansible_distribution == "Ubuntu"

- name:  CentOS -  Package cache update
  yum:
    name: '*'
    state: latest
  when: ansible_distribution == "CentOS"

- name: Server Dependencies
  package:
    name: "{{ item }}"
    state: present
  loop:
    - unzip
